version = 0.1
[ec2-user]
[ec2-user.deploy]
[ec2-user.deploy.parameters]
stack_name = "hello-world"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-uhklcl4mm2z3"
s3_prefix = "hello-world"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
